In [2]:
# tp avec le text en francais et en anglais 

import re 

with open("/Users/mohamedtbh/Desktop/M1_IA/TF_IDF/Eval_Formation_Etranger_fr.txt", "r") as file:
    content = file.read()
print(content)

content_splited = re.split(r"[.]" , content)

liste_of_sentences = list(content_splited)

print(f" the content splited :  {content_splited}")


list_of_tokens = []

for sentence in liste_of_sentences:
    tokens = sentence.split()
    list_of_tokens.append(tokens) 
    
print(list_of_tokens)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/mohamedtbh/Desktop/M1_IA/TF_IDF/Eval_Formation_Etranger_fr.txt'

In [7]:
# tp pour le text de obama et chiraq 

import re

def split_text_into_sentences_and_tokens(text):
    # Split the text into sentences using punctuation (.,!?)
    text = text.replace('�', '')
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    
    # Remove punctuation from sentences
    sentences_no_punctuation = [re.sub(r'[.,!-?;\'"]', '', sentence) for sentence in sentences]
    
    # Create a set to store tokens and avoid duplicates
    token_set = set()
    
    for sentence in sentences_no_punctuation:
        # Extract words only, excluding punctuation
        tokens = re.findall(r'\b\w+\b', sentence)
        token_set.update(token.lower() for token in tokens)
    
    # Convert the set to a list
    tokens = list(token_set)
    
    return sentences_no_punctuation, tokens




obama="""If there is anyone out there who still doubts that America is a place where all things are possible; who still wonders if the dream of our founders is alive in our time; who still questions the power of our democracy, tonight is your answer.
It's the answer told by lines that stretched around schools and churches in numbers this nation has never seen; by people who waited three hours and four hours, many for the very first time in their lives, because they believed that this time must be different; that their voice could be that difference.
It's the answer spoken by young and old, rich and poor, Democrat and Republican, black, white, Latino, Asian, Native American, gay, straight, disabled and not disabled  Americans who sent a message to the world that we have never been a collection of red states and blue states; we are, and always will be, the United States of America.
It's the answer that led those who have been told for so long by so many to be cynical, and fearful, and doubtful of what we can achieve to put their hands on the arc of history and bend it once more toward the hope of a better day.
It's been a long time coming, but tonight, because of what we did on this day, in this election, at this defining moment, change has come to America.
I just received a very gracious call from Sen. McCain. He fought long and hard in this campaign, and he's fought even longer and harder for the country he loves. He has endured sacrifices for America that most of us cannot begin to imagine, and we are better off for the service rendered by this brave and selfless leader. I congratulate him and Gov. Palin for all they have achieved, and I look forward to working with them to renew this nation's promise in the months ahead.
I want to thank my partner in this journey, a man who campaigned from his heart and spoke for the men and women he grew up with on the streets of Scranton and rode with on that train home to Delaware, the vice-president-elect of the United States, Joe Biden.
I would not be standing here tonight without the unyielding support of my best friend for the last 16 years, the rock of our family and the love of my life, our nation's next first lady, Michelle Obama. Sasha and Malia, I love you both so much, and you have earned the new puppy that's coming with us to the White House. And while she's no longer with us, I know my grandmother is watching, along with the family that made me who I am. I miss them tonight, and know that my debt to them is beyond measure.
To my campaign manager, David Plouffe; my chief strategist, David Axelrod; and the best campaign team ever assembled in the history of politics  you made this happen, and I am forever grateful for what you've sacrificed to get it done.
But above all, I will never forget who this victory truly belongs to  it belongs to you.
I was never the likeliest candidate for this office. We didn't start with much money or many endorsements. Our campaign was not hatched in the halls of Washington  it began in the backyards of Des Moines and the living rooms of Concord and the front porches of Charleston.
It was built by working men and women who dug into what little savings they had to give $5 and $10 and $20 to this cause. It grew strength from the young people who rejected the myth of their generation's apathy; who left their homes and their families for jobs that offered little pay and less sleep; from the not-so-young people who braved the bitter cold and scorching heat to knock on the doors of perfect strangers; from the millions of Americans who volunteered and organized, and proved that more than two centuries later, a government of the people, by the people and for the people has not perished from this earth. This is your victory.
I know you didn't do this just to win an election, and I know you didn't do it for me. You did it because you understand the enormity of the task that lies ahead. For even as we celebrate tonight, we know the challenges that tomorrow will bring are the greatest of our lifetime  two wars, a planet in peril, the worst financial crisis in a century. Even as we stand here tonight, we know there are brave Americans waking up in the deserts of Iraq and the mountains of Afghanistan to risk their lives for us. There are mothers and fathers who will lie awake after their children fall asleep and wonder how they'll make the mortgage, or pay their doctor's bills, or save enough for college. There is new energy to harness and new jobs to be created; new schools to build and threats to meet and alliances to repair.
The road ahead will be long. Our climb will be steep. We may not get there in one year, or even one term, but America  I have never been more hopeful than I am tonight that we will get there. I promise you: We as a people will get there.
There will be setbacks and false starts. There are many who won't agree with every decision or policy I make as president, and we know that government can't solve every problem. But I will always be honest with you about the challenges we face. I will listen to you, especially when we disagree. And, above all, I will ask you join in the work of remaking this nation the only way it's been done in America for 221 years  block by block, brick by brick, callused hand by callused hand.
What began 21 months ago in the depths of winter must not end on this autumn night. This victory alone is not the change we seek  it is only the chance for us to make that change. And that cannot happen if we go back to the way things were. It cannot happen without you.
So let us summon a new spirit of patriotism; of service and responsibility where each of us resolves to pitch in and work harder and look after not only ourselves, but each other. Let us remember that if this financial crisis taught us anything, it's that we cannot have a thriving Wall Street while Main Street suffers. In this country, we rise or fall as one nation  as one people.
Let us resist the temptation to fall back on the same partisanship and pettiness and immaturity that has poisoned our politics for so long. Let us remember that it was a man from this state who first carried the banner of the Republican Party to the White House  a party founded on the values of self-reliance, individual liberty and national unity. Those are values we all share, and while the Democratic Party has won a great victory tonight, we do so with a measure of humility and determination to heal the divides that have held back our progress.
As Lincoln said to a nation far more divided than ours, "We are not enemies, but friends... Though passion may have strained, it must not break our bonds of affection." And, to those Americans whose support I have yet to earn, I may not have won your vote, but I hear your voices, I need your help, and I will be your president, too.
And to all those watching tonight from beyond our shores, from parliaments and palaces to those who are huddled around radios in the forgotten corners of our world  our stories are singular, but our destiny is shared, and a new dawn of American leadership is at hand. To those who would tear this world down: We will defeat you. To those who seek peace and security: We support you. And to all those who have wondered if America's beacon still burns as bright: Tonight, we proved once more that the true strength of our nation comes not from the might of our arms or the scale of our wealth, but from the enduring power of our ideals: democracy, liberty, opportunity and unyielding hope.
For that is the true genius of America  that America can change. Our union can be perfected. And what we have already achieved gives us hope for what we can and must achieve tomorrow.
This election had many firsts and many stories that will be told for generations. But one that's on my mind tonight is about a woman who cast her ballot in Atlanta. She's a lot like the millions of others who stood in line to make their voice heard in this election, except for one thing: Ann Nixon Cooper is 106 years old.
She was born just a generation past slavery; a time when there were no cars on the road or planes in the sky; when someone like her couldn't vote for two reasons  because she was a woman and because of the color of her skin.
And tonight, I think about all that she's seen throughout her century in America  the heartache and the hope; the struggle and the progress; the times we were told that we can't and the people who pressed on with that American creed: Yes, we can.
At a time when women's voices were silenced and their hopes dismissed, she lived to see them stand up and speak out and reach for the ballot. Yes, we can.
When there was despair in the Dust Bowl and depression across the land, she saw a nation conquer fear itself with a New Deal, new jobs and a new sense of common purpose. Yes, we can.
When the bombs fell on our harbor and tyranny threatened the world, she was there to witness a generation rise to greatness and a democracy was saved. Yes, we can.
She was there for the buses in Montgomery, the hoses in Birmingham, a bridge in Selma and a preacher from Atlanta who told a people that "We Shall Overcome." Yes, we can.
A man touched down on the moon, a wall came down in Berlin, a world was connected by our own science and imagination. And this year, in this election, she touched her finger to a screen and cast her vote, because after 106 years in America, through the best of times and the darkest of hours, she knows how America can change. Yes, we can.
America, we have come so far. We have seen so much. But there is so much more to do. So tonight, let us ask ourselves: If our children should live to see the next century; if my daughters should be so lucky to live as long as Ann Nixon Cooper, what change will they see? What progress will we have made?
This is our chance to answer that call. This is our moment. This is our time  to put our people back to work and open doors of opportunity for our kids; to restore prosperity and promote the cause of peace; to reclaim the American Dream and reaffirm that fundamental truth that out of many, we are one; that while we breathe, we hope, and where we are met with cynicism, and doubt, and those who tell us that we can't, we will respond with that timeless creed that sums up the spirit of a people: Yes, we can.
Thank you, God bless you, and may God bless the United States of America."""



chiraq = """
La confiance que vous venez de me témoigner, je veux y répondre en m'engageant dans l'action avec détermination.
Mes chers compatriotes de métropole, d'outre-mer et de l'étranger,
Nous venons de vivre un temps de grave inquiétude pour la Nation.
Mais ce soir, dans un grand élan la France a réaffirmé son attachement aux valeurs de la République.
Je salue la France, fidèle à elle-même, fidèle à ses grands idéaux, fidèle à sa vocation universelle et humaniste.
Je salue la France qui, comme toujours dans les moments difficiles, sait se retrouver sur l'essentiel. Je salue les Françaises et les Français épris de solidarité et de liberté, soucieux de s'ouvrir à l'Europe et au monde, tournés vers l'avenir.
J'ai entendu et compris votre appel pour que la République vive, pour que la Nation se rassemble, pour que la politique change. Tout dans l'action qui sera conduite, devra répondre à cet appel et s'inspirer d'une exigence de service et d'écoute pour chaque Française et chaque Français.
Ce soir, je veux vous dire aussi mon émotion et le sentiment que j'ai de la responsabilité qui m'incombe.
Votre choix d'aujourd'hui est un choix fondateur, un choix qui renouvelle notre pacte républicain. Ce choix m'oblige comme il oblige chaque responsable de notre pays. Chacun mesure bien, à l'aune de notre histoire, la force de ce moment exceptionnel.
Votre décision, vous l'avez prise en conscience, en dépassant les clivages traditionnels, et, pour certains d'entre vous, en allant au-delà même de vos préférences personnelles ou politiques.
La confiance que vous venez de me témoigner, je veux y répondre en m'engageant dans l'action avec détermination.
Président de tous les Français, je veux y répondre dans un esprit de rassemblement. Je veux mettre la République au service de tous. Je veux que les valeurs de liberté, d'égalité et de fraternité reprennent toute leur place dans la vie de chacune et de chacun d'entre nous.
La liberté, c'est la sécurité, la lutte contre la violence, le refus de l'impunité. Faire reculer l'insécurité est la première priorité de l'Etat pour les temps à venir.
La liberté, c'est aussi la reconnaissance du travail et du mérite, la réduction des charges et des impôts.
L'égalité, c'est le refus de toute discrimination, ce sont les mêmes droits et les mêmes devoirs pour tous.
La fraternité, c'est sauvegarder les retraites. C'est aider les familles à jouer pleinement leur rôle. C'est faire en sorte que personne n'éprouve plus le sentiment d'être laissé pour compte.
La France, forte de sa cohésion sociale et de son dynamisme économique, portera en Europe et dans le monde l'ambition de la paix, des libertés et de la solidarité.
Dans les prochains jours, je mettrai en place un gouvernement de mission, un gouvernement qui aura pour seule tâche de répondre à vos préoccupations et d'apporter des solutions à des problèmes trop longtemps négligés. Son premier devoir sera de rétablir l'autorité de l'Etat pour répondre à l'exigence de sécurité, et de mettre la France sur un nouveau chemin de croissance et d'emploi.
C'est par une action forte et déterminée, c'est par la solidarité de la Nation, c'est par l'efficacité des résultats obtenus, que nous pourrons lutter contre l'intolérance, faire reculer l'extrémisme, garantir la vitalité de notre démocratie. Cette exigence s'impose à chacun d'entre nous. Elle impliquera, au cours des prochaines années, vigilance et mobilisation de la part de tous.
Mes chers compatriotes,
Le mandat que vous m'avez confié, je l'exercerai dans un esprit d'ouverture et de concorde, avec pour exigence l'unité de la République, la cohésion de la Nation et le respect de l'autorité de l'Etat.
Les jours que nous venons de vivre ont ranimé la vigueur nationale, la vigueur de l'idéal démocratique français. Ils ont exprimé une autre idée de la politique, une autre idée de la citoyenneté.
Chacune et chacun d'entre vous, conscient de ses responsabilités, par un choix de liberté, a contribué, ce soir, à forger le destin de la France.
Il y a là un espoir qui ne demande qu'à grandir, un espoir que je veux servir.
Vive la République !
Vive la France !
"""

sentences_no_punctuation, tokens = split_text_into_sentences_and_tokens(obama)

print('Obama')
print(f"sentences obama : {sentences_no_punctuation}")
print(f"tokens obama : {tokens}")


print(len(sentences_no_punctuation))
print(len(tokens))




Obama
sentences obama : ['If there is anyone out there who still doubts that America is a place where all things are possible who still wonders if the dream of our founders is alive in our time who still questions the power of our democracy tonight is your answer', 'Its the answer told by lines that stretched around schools and churches in numbers this nation has never seen by people who waited three hours and four hours many for the very first time in their lives because they believed that this time must be different that their voice could be that difference', 'Its the answer spoken by young and old rich and poor Democrat and Republican black white Latino Asian Native American gay straight disabled and not disabled  Americans who sent a message to the world that we have never been a collection of red states and blue states we are and always will be the United States of America', 'Its the answer that led those who have been told for so long by so many to be cynical and fearful and doub

In [8]:
sentences_no_punctuation, tokens = split_text_into_sentences_and_tokens(chiraq)

print('CHIRAQ')
print(f"sentences chiraq : {sentences_no_punctuation}")
print(f"tokens chiraq : {tokens}")


print(len(sentences_no_punctuation))
print(len(tokens))


CHIRAQ
sentences chiraq : ['La confiance que vous venez de me témoigner je veux y répondre en mengageant dans laction avec détermination', 'Mes chers compatriotes de métropole doutremer et de létranger\nNous venons de vivre un temps de grave inquiétude pour la Nation', 'Mais ce soir dans un grand élan la France a réaffirmé son attachement aux valeurs de la République', 'Je salue la France fidèle à ellemême fidèle à ses grands idéaux fidèle à sa vocation universelle et humaniste', 'Je salue la France qui comme toujours dans les moments difficiles sait se retrouver sur lessentiel', 'Je salue les Françaises et les Français épris de solidarité et de liberté soucieux de souvrir à lEurope et au monde tournés vers lavenir', 'Jai entendu et compris votre appel pour que la République vive pour que la Nation se rassemble pour que la politique change', 'Tout dans laction qui sera conduite devra répondre à cet appel et sinspirer dune exigence de service et découte pour chaque Française et chaque F

In [9]:
import re
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform

# 1. Diviser le texte en phrases
def split_into_sentences(text):
    # Utilisation d'une expression régulière pour diviser les phrases sur les points, points d'exclamation, points d'interrogation
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    return sentences

# 2. Prétraitement du texte
def preprocess_text(sentences):
    unique_tokens = set()  # Utiliser un ensemble pour les mots uniques
    for sentence in sentences:
        # Nettoyer et tokeniser
        tokens = re.findall(r'\b\w+\b', sentence.lower())
        unique_tokens.update(tokens)  # Ajouter les mots uniques
    return sorted(unique_tokens)  # Retourner une liste triée

# 3. Créer la matrice binaire et la matrice d'occurrences
def create_matrices(sentences, unique_tokens):
    binary_matrix = []
    occurrence_matrix = []
    
    for sentence in sentences:
        # Tokeniser la phrase
        tokens = re.findall(r'\b\w+\b', sentence.lower())
        
        # Créer une ligne pour la matrice binaire
        binary_row = [1 if token in tokens else 0 for token in unique_tokens]
        binary_matrix.append(binary_row)
        
        # Créer une ligne pour la matrice d'occurrences
        occurrence_row = [tokens.count(token) for token in unique_tokens]
        occurrence_matrix.append(occurrence_row)

    return np.array(binary_matrix), np.array(occurrence_matrix)

# 4. Calculer la distance de Manhattan
def calculate_manhattan_distance(matrix):
    return squareform(pdist(matrix, metric='cityblock'))

# 5. Calculer la distance euclidienne
def calculate_euclidean_distance(matrix):
    return squareform(pdist(matrix, metric='euclidean'))

# Exemple de texte


# Traitement des phrases
sentences = split_into_sentences(chiraq)
unique_tokens = preprocess_text(sentences)

# Création des matrices
binary_matrix, occurrence_matrix = create_matrices(sentences, unique_tokens)

# Calculer les distances de Manhattan
binary_distance_manhattan = calculate_manhattan_distance(binary_matrix)
occurrence_distance_manhattan = calculate_manhattan_distance(occurrence_matrix)

# Calculer les distances euclidiennes
binary_distance_euclidean = calculate_euclidean_distance(binary_matrix)
occurrence_distance_euclidean = calculate_euclidean_distance(occurrence_matrix)

# Créer des DataFrames pour afficher les distances
binary_distance_manhattan_df = pd.DataFrame(binary_distance_manhattan, 
                                             columns=[f'Doc {i+1}' for i in range(len(sentences))],
                                             index=[f'Doc {i+1}' for i in range(len(sentences))])

occurrence_distance_manhattan_df = pd.DataFrame(occurrence_distance_manhattan, 
                                                columns=[f'Doc {i+1}' for i in range(len(sentences))],
                                                index=[f'Doc {i+1}' for i in range(len(sentences))])

binary_distance_euclidean_df = pd.DataFrame(binary_distance_euclidean, 
                                             columns=[f'Doc {i+1}' for i in range(len(sentences))],
                                             index=[f'Doc {i+1}' for i in range(len(sentences))])

occurrence_distance_euclidean_df = pd.DataFrame(occurrence_distance_euclidean, 
                                                columns=[f'Doc {i+1}' for i in range(len(sentences))],
                                                index=[f'Doc {i+1}' for i in range(len(sentences))])

# Affichage des DataFrames pour vérifier les résultats
print(binary_distance_manhattan_df)
print(occurrence_distance_manhattan_df)
print(binary_distance_euclidean_df)
print(occurrence_distance_euclidean_df)


        Doc 1  Doc 2  Doc 3  Doc 4  Doc 5  Doc 6  Doc 7  Doc 8  Doc 9  Doc 10  \
Doc 1     0.0   35.0   31.0   32.0   29.0   35.0   33.0   35.0   27.0    33.0   
Doc 2    35.0    0.0   32.0   33.0   34.0   36.0   30.0   36.0   36.0    30.0   
Doc 3    31.0   32.0    0.0   29.0   28.0   36.0   30.0   38.0   30.0    28.0   
Doc 4    32.0   33.0   29.0    0.0   25.0   29.0   29.0   37.0   31.0    29.0   
Doc 5    29.0   34.0   28.0   25.0    0.0   30.0   30.0   36.0   32.0    28.0   
Doc 6    35.0   36.0   36.0   29.0   30.0    0.0   36.0   34.0   36.0    34.0   
Doc 7    33.0   30.0   30.0   29.0   30.0   36.0    0.0   36.0   28.0    28.0   
Doc 8    35.0   36.0   38.0   37.0   36.0   34.0   36.0    0.0   40.0    34.0   
Doc 9    27.0   36.0   30.0   31.0   32.0   36.0   28.0   40.0    0.0    32.0   
Doc 10   33.0   30.0   28.0   29.0   28.0   34.0   28.0   34.0   32.0     0.0   
Doc 11   27.0   30.0   24.0   27.0   26.0   30.0   28.0   32.0   26.0    20.0   
Doc 12   28.0   29.0   25.0 

In [10]:

# Afficher les résultats
print("Matrice Binaire (Bag of Words) :")
print(binary_matrix)



Matrice Binaire (Bag of Words) :
[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
print("\nMatrice d'Occurrences (Bag of Words) :")
print(occurrence_matrix)




Matrice d'Occurrences (Bag of Words) :
[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [12]:
def calculate_similarity_matrix(distance_matrix):
    max_distance = np.max(distance_matrix)
    return 1 - (distance_matrix / max_distance)

In [13]:

# Afficher les résultats
print("Matrice Binaire (Bag of Words) :")
print(binary_matrix)



Matrice Binaire (Bag of Words) :
[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
print("\nMatrice de Distance de Manhattan (Binaire) :")
print(binary_distance_manhattan_df)




Matrice de Distance de Manhattan (Binaire) :
        Doc 1  Doc 2  Doc 3  Doc 4  Doc 5  Doc 6  Doc 7  Doc 8  Doc 9  Doc 10  \
Doc 1     0.0   35.0   31.0   32.0   29.0   35.0   33.0   35.0   27.0    33.0   
Doc 2    35.0    0.0   32.0   33.0   34.0   36.0   30.0   36.0   36.0    30.0   
Doc 3    31.0   32.0    0.0   29.0   28.0   36.0   30.0   38.0   30.0    28.0   
Doc 4    32.0   33.0   29.0    0.0   25.0   29.0   29.0   37.0   31.0    29.0   
Doc 5    29.0   34.0   28.0   25.0    0.0   30.0   30.0   36.0   32.0    28.0   
Doc 6    35.0   36.0   36.0   29.0   30.0    0.0   36.0   34.0   36.0    34.0   
Doc 7    33.0   30.0   30.0   29.0   30.0   36.0    0.0   36.0   28.0    28.0   
Doc 8    35.0   36.0   38.0   37.0   36.0   34.0   36.0    0.0   40.0    34.0   
Doc 9    27.0   36.0   30.0   31.0   32.0   36.0   28.0   40.0    0.0    32.0   
Doc 10   33.0   30.0   28.0   29.0   28.0   34.0   28.0   34.0   32.0     0.0   
Doc 11   27.0   30.0   24.0   27.0   26.0   30.0   28.0   32.0 

In [15]:
print("\nMatrice de Distance de Manhattan (Occurrences) :")
print(occurrence_distance_manhattan_df)




Matrice de Distance de Manhattan (Occurrences) :
        Doc 1  Doc 2  Doc 3  Doc 4  Doc 5  Doc 6  Doc 7  Doc 8  Doc 9  Doc 10  \
Doc 1     0.0   38.0   32.0   36.0   29.0   41.0   39.0   39.0   27.0    36.0   
Doc 2    38.0    0.0   36.0   40.0   37.0   41.0   39.0   43.0   39.0    36.0   
Doc 3    32.0   36.0    0.0   34.0   29.0   43.0   35.0   43.0   31.0    32.0   
Doc 4    36.0   40.0   34.0    0.0   29.0   39.0   39.0   45.0   35.0    36.0   
Doc 5    29.0   37.0   29.0   29.0    0.0   36.0   36.0   40.0   32.0    31.0   
Doc 6    41.0   41.0   43.0   39.0   36.0    0.0   48.0   40.0   42.0    43.0   
Doc 7    39.0   39.0   35.0   39.0   36.0   48.0    0.0   46.0   34.0    37.0   
Doc 8    39.0   43.0   43.0   45.0   40.0   40.0   46.0    0.0   44.0    41.0   
Doc 9    27.0   39.0   31.0   35.0   32.0   42.0   34.0   44.0    0.0    35.0   
Doc 10   36.0   36.0   32.0   36.0   31.0   43.0   37.0   41.0   35.0     0.0   
Doc 11   28.0   34.0   26.0   32.0   27.0   37.0   35.0   3

In [16]:
print("\nMatrice de Distance Euclidienne (Binaire) :")
print(binary_distance_euclidean_df)

print("\nMatrice de Distance Euclidienne (Occurrences) :")
print(occurrence_distance_euclidean_df)




Matrice de Distance Euclidienne (Binaire) :
           Doc 1     Doc 2     Doc 3     Doc 4     Doc 5     Doc 6     Doc 7  \
Doc 1   0.000000  5.916080  5.567764  5.656854  5.385165  5.916080  5.744563   
Doc 2   5.916080  0.000000  5.656854  5.744563  5.830952  6.000000  5.477226   
Doc 3   5.567764  5.656854  0.000000  5.385165  5.291503  6.000000  5.477226   
Doc 4   5.656854  5.744563  5.385165  0.000000  5.000000  5.385165  5.385165   
Doc 5   5.385165  5.830952  5.291503  5.000000  0.000000  5.477226  5.477226   
Doc 6   5.916080  6.000000  6.000000  5.385165  5.477226  0.000000  6.000000   
Doc 7   5.744563  5.477226  5.477226  5.385165  5.477226  6.000000  0.000000   
Doc 8   5.916080  6.000000  6.164414  6.082763  6.000000  5.830952  6.000000   
Doc 9   5.196152  6.000000  5.477226  5.567764  5.656854  6.000000  5.291503   
Doc 10  5.744563  5.477226  5.291503  5.385165  5.291503  5.830952  5.291503   
Doc 11  5.196152  5.477226  4.898979  5.196152  5.099020  5.477226  5.29150

In [17]:
#Matrice de similarité
def calculate_similarity_matrix(distance_matrix):
    max_distance = np.max(distance_matrix)
    return 1 - (distance_matrix / max_distance)
# Calculer les matrices de similarité
binary_similarity_manhattan = calculate_similarity_matrix(binary_distance_manhattan)
occurrence_similarity_manhattan = calculate_similarity_matrix(occurrence_distance_manhattan)

binary_similarity_euclidean = calculate_similarity_matrix(binary_distance_euclidean)
occurrence_similarity_euclidean = calculate_similarity_matrix(occurrence_distance_euclidean)

# Afficher les DataFrames des similarités
print("Matrice de similarité (Binaire - Manhattan):")
print(binary_similarity_manhattan)

print("\nMatrice de similarité (Occurrence - Manhattan):")
print(occurrence_similarity_manhattan)



Matrice de similarité (Binaire - Manhattan):
[[1.         0.35185185 0.42592593 ... 0.48148148 0.61111111 0.61111111]
 [0.35185185 1.         0.40740741 ... 0.35185185 0.59259259 0.59259259]
 [0.42592593 0.40740741 1.         ... 0.46296296 0.7037037  0.7037037 ]
 ...
 [0.48148148 0.35185185 0.46296296 ... 1.         0.64814815 0.64814815]
 [0.61111111 0.59259259 0.7037037  ... 0.64814815 1.         0.96296296]
 [0.61111111 0.59259259 0.7037037  ... 0.64814815 0.96296296 1.        ]]

Matrice de similarité (Occurrence - Manhattan):
[[1.         0.44117647 0.52941176 ... 0.55882353 0.69117647 0.69117647]
 [0.44117647 1.         0.47058824 ... 0.41176471 0.63235294 0.63235294]
 [0.52941176 0.47058824 1.         ... 0.52941176 0.75       0.75      ]
 ...
 [0.55882353 0.41176471 0.52941176 ... 1.         0.69117647 0.69117647]
 [0.69117647 0.63235294 0.75       ... 0.69117647 1.         0.97058824]
 [0.69117647 0.63235294 0.75       ... 0.69117647 0.97058824 1.        ]]


In [18]:
def K_plus_proches_documents(doc_requete, k, similarity_matrix):
    """
    Retourne les k premiers documents les plus similaires au document de requête.
    """
    # Extraire les similarités du document de requête
    similarites = similarity_matrix[doc_requete]
    
    # Créer une liste d'index et de similarités
    similarites_idx = [(i, similarites[i]) for i in range(len(similarites)) if i != doc_requete]
    
    # de plus élevée à plus basse
    similarites_idx.sort(key=lambda x: x[1], reverse=True)
    
    # Retourner les k premiers documents
    return similarites_idx[:k]


user_input = int(input("Entrez le numéro du document : "))-1
k = int(input("Entrez le nombre de documents similaires à retourner : "))
# par exemple je choisis: matrice similarite de manhattan
k_plus_proches = K_plus_proches_documents(user_input, k, binary_similarity_manhattan)

print(f"Les {k} documents les plus similaires au document {user_input + 1} :")
for idx, sim in k_plus_proches:
    print(f"Document {idx + 1} avec similarité de {sim:.4f}")


Les 4 documents les plus similaires au document 1 :
Document 14 avec similarité de 1.0000
Document 15 avec similarité de 0.6111
Document 16 avec similarité de 0.6111
Document 36 avec similarité de 0.6111


## pour exemple de (cat,dog) 


In [12]:
import re
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform

# Phrases d'entrée
ph1_ = "The cat sat on the mat. The cat sat on the mat."
ph2_ = "The dog sat on the log. The dog sat on the log."
ph3_ = "Cats and dogs are great pets. Cats and dogs are great pets."


# 1. Découper les phrases en phrases individuelles
def split_into_sentences(text):
    """Divise le texte en phrases en utilisant la ponctuation."""
    sentences = re.split(r'\.', text)
    return [sentence.strip() for sentence in sentences if sentence.strip()]

# 2. Prétraitement du texte pour obtenir les mots uniques
def preprocess_text(sentences):
    unique_tokens = set()  # Utilisation d'un ensemble pour éviter les doublons
    for sentence in sentences:
        # Nettoyer et tokeniser
        tokens = re.findall(r'\b\w+\b', sentence.lower())
        unique_tokens.update(tokens)  # Ajouter les mots uniques
    return sorted(unique_tokens)  # Retourner une liste triée

# 3. Créer la matrice binaire et la matrice d'occurrences
def create_matrices(sentences, unique_tokens):
    binary_matrix = []
    occurrence_matrix = []
    
    for sentence in sentences:
        # Tokeniser la phrase
        tokens = re.findall(r'\b\w+\b', sentence.lower())
        
        # Créer une ligne pour la matrice binaire
        binary_row = [1 if token in tokens else 0 for token in unique_tokens]
        binary_matrix.append(binary_row)
        
        # Créer une ligne pour la matrice d'occurrences
        occurrence_row = [tokens.count(token) for token in unique_tokens]
        occurrence_matrix.append(occurrence_row)

    return np.array(binary_matrix), np.array(occurrence_matrix)

# 4. Calculer la distance de Manhattan
def calculate_manhattan_distance(matrix):
    return squareform(pdist(matrix, metric='cityblock'))

# 5. Calculer la distance euclidienne
def calculate_euclidean_distance(matrix):
    return squareform(pdist(matrix, metric='euclidean'))

# Traitement des phrases
sentences = [ph1_, ph2_, ph3_]  # Les documents à comparer
tokenized_sentences = [split_into_sentences(doc) for doc in sentences]  # Diviser chaque doc en phrases
all_sentences = [sentence for doc in tokenized_sentences for sentence in doc]  # Toutes les phrases ensemble

# Prétraitement pour obtenir les tokens uniques
unique_tokens = preprocess_text(all_sentences)

# Création des matrices binaires et d'occurrences pour ph1_, ph2_, et ph3_
binary_matrix, occurrence_matrix = create_matrices([ph1_, ph2_, ph3_], unique_tokens)

# Calculer les distances de Manhattan
binary_distance_manhattan = calculate_manhattan_distance(binary_matrix)
occurrence_distance_manhattan = calculate_manhattan_distance(occurrence_matrix)

# Calculer les distances euclidiennes
binary_distance_euclidean = calculate_euclidean_distance(binary_matrix)
occurrence_distance_euclidean = calculate_euclidean_distance(occurrence_matrix)

# Créer des DataFrames pour afficher les distances
binary_distance_manhattan_df = pd.DataFrame(binary_distance_manhattan, 
                                            columns=['ph1_', 'ph2_', 'ph3_'],
                                            index=['ph1_', 'ph2_', 'ph3_'])

occurrence_distance_manhattan_df = pd.DataFrame(occurrence_distance_manhattan, 
                                                columns=['ph1_', 'ph2_', 'ph3_'],
                                                index=['ph1_', 'ph2_', 'ph3_'])

binary_distance_euclidean_df = pd.DataFrame(binary_distance_euclidean, 
                                            columns=['ph1_', 'ph2_', 'ph3_'],
                                            index=['ph1_', 'ph2_', 'ph3_'])

occurrence_distance_euclidean_df = pd.DataFrame(occurrence_distance_euclidean, 
                                                columns=['ph1_', 'ph2_', 'ph3_'],
                                                index=['ph1_', 'ph2_', 'ph3_'])

# Afficher les résultats
print("\nMatrice de Distance de Manhattan (Binaire) :")
print(binary_distance_manhattan_df)

print("\nMatrice de Distance de Manhattan (Occurrences) :")
print(occurrence_distance_manhattan_df)

print("\nMatrice de Distance Euclidienne (Binaire) :")
print(binary_distance_euclidean_df)

print("\nMatrice de Distance Euclidienne (Occurrences) :")
print(occurrence_distance_euclidean_df)



Matrice de Distance de Manhattan (Binaire) :
      ph1_  ph2_  ph3_
ph1_   0.0   4.0  11.0
ph2_   4.0   0.0  11.0
ph3_  11.0  11.0   0.0

Matrice de Distance de Manhattan (Occurrences) :
      ph1_  ph2_  ph3_
ph1_   0.0   8.0  24.0
ph2_   8.0   0.0  24.0
ph3_  24.0  24.0   0.0

Matrice de Distance Euclidienne (Binaire) :
          ph1_      ph2_      ph3_
ph1_  0.000000  2.000000  3.316625
ph2_  2.000000  0.000000  3.316625
ph3_  3.316625  3.316625  0.000000

Matrice de Distance Euclidienne (Occurrences) :
          ph1_      ph2_      ph3_
ph1_  0.000000  4.000000  7.483315
ph2_  4.000000  0.000000  7.483315
ph3_  7.483315  7.483315  0.000000


In [14]:

ph1_ = "The cat sat on the mat. The cat sat on the mat.The cat sat on the mat. The cat sat on the mat."
ph2_ = "The dog sat on the log. The dog sat on the log.The dog sat on the log. The dog sat on the log."
ph3_ = "Cats and dogs are great pets. Cats and dogs are great pets.Cats and dogs are great pets. Cats and dogs are great pets."

tokenized_sentences = [split_into_sentences(doc) for doc in sentences]  # Diviser chaque doc en phrases
all_sentences = [sentence for doc in tokenized_sentences for sentence in doc]  

# Prétraitement pour obtenir les tokens uniques
unique_tokens = preprocess_text(all_sentences)

# Création des matrices binaires et d'occurrences pour ph1_, ph2_, et ph3_
binary_matrix, occurrence_matrix = create_matrices([ph1_, ph2_, ph3_], unique_tokens)

# Calculer les distances de Manhattan
binary_distance_manhattan = calculate_manhattan_distance(binary_matrix)
occurrence_distance_manhattan = calculate_manhattan_distance(occurrence_matrix)

# Calculer les distances euclidiennes
binary_distance_euclidean = calculate_euclidean_distance(binary_matrix)
occurrence_distance_euclidean = calculate_euclidean_distance(occurrence_matrix)

# Créer des DataFrames pour afficher les distances
binary_distance_manhattan_df = pd.DataFrame(binary_distance_manhattan, 
                                            columns=['ph1_', 'ph2_', 'ph3_'],
                                            index=['ph1_', 'ph2_', 'ph3_'])

occurrence_distance_manhattan_df = pd.DataFrame(occurrence_distance_manhattan, 
                                                columns=['ph1_', 'ph2_', 'ph3_'],
                                                index=['ph1_', 'ph2_', 'ph3_'])

binary_distance_euclidean_df = pd.DataFrame(binary_distance_euclidean, 
                                            columns=['ph1_', 'ph2_', 'ph3_'],
                                            index=['ph1_', 'ph2_', 'ph3_'])

occurrence_distance_euclidean_df = pd.DataFrame(occurrence_distance_euclidean, 
                                                columns=['ph1_', 'ph2_', 'ph3_'],
                                                index=['ph1_', 'ph2_', 'ph3_'])

# Afficher les résultats
print("\nMatrice de Distance de Manhattan (Binaire) :")
print(binary_distance_manhattan_df)

print("\nMatrice de Distance de Manhattan (Occurrences) :")
print(occurrence_distance_manhattan_df)

print("\nMatrice de Distance Euclidienne (Binaire) :")
print(binary_distance_euclidean_df)

print("\nMatrice de Distance Euclidienne (Occurrences) :")
print(occurrence_distance_euclidean_df)



Matrice de Distance de Manhattan (Binaire) :
      ph1_  ph2_  ph3_
ph1_   0.0   4.0  11.0
ph2_   4.0   0.0  11.0
ph3_  11.0  11.0   0.0

Matrice de Distance de Manhattan (Occurrences) :
      ph1_  ph2_  ph3_
ph1_   0.0  16.0  48.0
ph2_  16.0   0.0  48.0
ph3_  48.0  48.0   0.0

Matrice de Distance Euclidienne (Binaire) :
          ph1_      ph2_      ph3_
ph1_  0.000000  2.000000  3.316625
ph2_  2.000000  0.000000  3.316625
ph3_  3.316625  3.316625  0.000000

Matrice de Distance Euclidienne (Occurrences) :
          ph1_      ph2_      ph3_
ph1_   0.00000   8.00000  14.96663
ph2_   8.00000   0.00000  14.96663
ph3_  14.96663  14.96663   0.00000


In [20]:
###new ###################################
# import re
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform, hamming
from sklearn.metrics import jaccard_score
from sklearn.feature_extraction.text import CountVectorizer

# Phrases d'entrée
ph1_ = "The cat sat on the mat."
ph2_ = "The dog sat on the log."
ph3_ = "Cats and dogs are great pets."
documents = [ph1_, ph2_, ph3_]

# 1. Découper les phrases en phrases individuelles
def split_into_sentences(text):
    """Divise le texte en phrases en utilisant la ponctuation."""
    sentences = re.split(r'\.', text)
    return [sentence.strip() for sentence in sentences if sentence.strip()]

# 2. Prétraitement du texte pour obtenir les mots uniques
def preprocess_text(sentences):
    unique_tokens = set()  # Utilisation d'un ensemble pour éviter les doublons
    for sentence in sentences:
        # Nettoyer et tokeniser
        tokens = re.findall(r'\b\w+\b', sentence.lower())
        unique_tokens.update(tokens)  # Ajouter les mots uniques
    return sorted(unique_tokens)  # Retourner une liste triée

# 3. Créer la matrice binaire et la matrice d'occurrences
def create_matrices(sentences, unique_tokens):
    binary_matrix = []
    occurrence_matrix = []
    
    for sentence in sentences:
        # Tokeniser la phrase
        tokens = re.findall(r'\b\w+\b', sentence.lower())
        
        # Créer une ligne pour la matrice binaire
        binary_row = [1 if token in tokens else 0 for token in unique_tokens]
        binary_matrix.append(binary_row)
        
        # Créer une ligne pour la matrice d'occurrences
        occurrence_row = [tokens.count(token) for token in unique_tokens]
        occurrence_matrix.append(occurrence_row)

    return np.array(binary_matrix), np.array(occurrence_matrix)

# 4. Calculer la distance de Manhattan
def calculate_manhattan_distance(matrix):
    return squareform(pdist(matrix, metric='cityblock'))

# 5. Calculer la distance euclidienne
def calculate_euclidean_distance(matrix):
    return squareform(pdist(matrix, metric='euclidean'))

# 6. Normalisation en probabilités
def normalize_matrix(matrix):
    """Normalise chaque ligne de la matrice en probabilités (fréquences relatives)."""
    row_sums = matrix.sum(axis=1, keepdims=True)
    return matrix / row_sums

# Prétraitement : Obtenir les tokens uniques
unique_tokens = preprocess_text(documents)

# Création des matrices binaires et d'occurrences pour les phrases
binary_matrix, occurrence_matrix = create_matrices(documents, unique_tokens)

# Calculer les distances de Manhattan et Euclidienne
binary_distance_manhattan = calculate_manhattan_distance(binary_matrix)
occurrence_distance_manhattan = calculate_manhattan_distance(occurrence_matrix)
binary_distance_euclidean = calculate_euclidean_distance(binary_matrix)
occurrence_distance_euclidean = calculate_euclidean_distance(occurrence_matrix)

# Normalisation de la matrice d'occurrences en probabilités
normalized_matrix = normalize_matrix(occurrence_matrix)
distance_euclidean_normalized = calculate_euclidean_distance(normalized_matrix)

# Calculer la distance de Jaccard entre les phrases
vectorizer = CountVectorizer(binary=True)
X_binary = vectorizer.fit_transform(documents).toarray()

jaccard_distances = np.zeros((len(documents), len(documents)))
for i in range(len(documents)):
    for j in range(len(documents)):
        jaccard_distances[i, j] = 1 - jaccard_score(X_binary[i], X_binary[j])

# Calculer la distance de Hamming entre les phrases
hamming_distances = squareform(pdist(X_binary, metric='hamming'))

# Création des DataFrames pour afficher les matrices de distances
binary_distance_manhattan_df = pd.DataFrame(binary_distance_manhattan, 
                                            columns=['ph1_', 'ph2_', 'ph3_'],
                                            index=['ph1_', 'ph2_', 'ph3_'])

occurrence_distance_manhattan_df = pd.DataFrame(occurrence_distance_manhattan, 
                                                columns=['ph1_', 'ph2_', 'ph3_'],
                                                index=['ph1_', 'ph2_', 'ph3_'])

binary_distance_euclidean_df = pd.DataFrame(binary_distance_euclidean, 
                                            columns=['ph1_', 'ph2_', 'ph3_'],
                                            index=['ph1_', 'ph2_', 'ph3_'])

occurrence_distance_euclidean_df = pd.DataFrame(occurrence_distance_euclidean, 
                                                columns=['ph1_', 'ph2_', 'ph3_'],
                                                index=['ph1_', 'ph2_', 'ph3_'])

distance_euclidean_normalized_df = pd.DataFrame(distance_euclidean_normalized, 
                                                columns=['ph1_', 'ph2_', 'ph3_'],
                                                index=['ph1_', 'ph2_', 'ph3_'])

jaccard_distances_df = pd.DataFrame(jaccard_distances, 
                                    columns=['ph1_', 'ph2_', 'ph3_'],
                                    index=['ph1_', 'ph2_', 'ph3_'])

hamming_distances_df = pd.DataFrame(hamming_distances, 
                                    columns=['ph1_', 'ph2_', 'ph3_'],
                                    index=['ph1_', 'ph2_', 'ph3_'])

# Afficher les résultats
print("\nMatrice de Distance de Manhattan (Binaire) :")
print(binary_distance_manhattan_df)

print("\nMatrice de Distance de Manhattan (Occurrences) :")
print(occurrence_distance_manhattan_df)

print("\nMatrice de Distance Euclidienne (Binaire) :")
print(binary_distance_euclidean_df)

print("\nMatrice de Distance Euclidienne (Occurrences) :")
print(occurrence_distance_euclidean_df)

print("\nMatrice de Distance Euclidienne (Normalisée en Probabilités) :")
print(distance_euclidean_normalized_df)

print("\nMatrice de Distance de Jaccard :")
print(jaccard_distances_df)

print("\nMatrice de Distance de Hamming :")
print(hamming_distances_df)



Matrice de Distance de Manhattan (Binaire) :
      ph1_  ph2_  ph3_
ph1_   0.0   4.0  11.0
ph2_   4.0   0.0  11.0
ph3_  11.0  11.0   0.0

Matrice de Distance de Manhattan (Occurrences) :
      ph1_  ph2_  ph3_
ph1_   0.0   4.0  12.0
ph2_   4.0   0.0  12.0
ph3_  12.0  12.0   0.0

Matrice de Distance Euclidienne (Binaire) :
          ph1_      ph2_      ph3_
ph1_  0.000000  2.000000  3.316625
ph2_  2.000000  0.000000  3.316625
ph3_  3.316625  3.316625  0.000000

Matrice de Distance Euclidienne (Occurrences) :
          ph1_      ph2_      ph3_
ph1_  0.000000  2.000000  3.741657
ph2_  2.000000  0.000000  3.741657
ph3_  3.741657  3.741657  0.000000

Matrice de Distance Euclidienne (Normalisée en Probabilités) :
          ph1_      ph2_     ph3_
ph1_  0.000000  0.333333  0.62361
ph2_  0.333333  0.000000  0.62361
ph3_  0.623610  0.623610  0.00000

Matrice de Distance de Jaccard :
          ph1_      ph2_  ph3_
ph1_  0.000000  0.571429   1.0
ph2_  0.571429  0.000000   1.0
ph3_  1.000000  1.0

In [13]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from scipy.spatial.distance import braycurtis
from scipy.special import kl_div

# Phrases d'entrée
ph1_ = "The cat sat on the mat."
ph2_ = "The dog sat on the log."
ph3_ = "Cats and dogs are great pets."
###The cat sat on the mat.  The dog sat on the log. Cats and dogs are great pets.
# Documents
documents = [ph1_, ph2_, ph3_]

# Vectorisation des documents pour obtenir les matrices d'occurrence
vectorizer_occ = CountVectorizer(binary=False)
occurrence_matrix = vectorizer_occ.fit_transform(documents).toarray()

# Vectorisation binaire (présence/absence de mots)
vectorizer_binary = CountVectorizer(binary=True)
binary_matrix = vectorizer_binary.fit_transform(documents).toarray()

# Fonction de normalisation L1
def normalize_L1(matrix):
    return matrix / matrix.sum(axis=1, keepdims=True)

# Fonction de normalisation L2
def normalize_L2(matrix):
    return matrix / np.sqrt((matrix ** 2).sum(axis=1, keepdims=True))

# Calcul de la distance Bray-Curtis entre deux vecteurs
def bray_curtis_distance(v1, v2):
    return braycurtis(v1, v2)

# Calcul de la distance Kullback-Leibler entre deux vecteurs
def kullback_leibler_distance(v1, v2):
    # Ajout de petites constantes pour éviter la division par zéro
    v1 = np.clip(v1, 1e-10, None)
    v2 = np.clip(v2, 1e-10, None)
    return np.sum(kl_div(v1, v2))

# Normalisation des matrices
normalized_occ_matrix_L1 = normalize_L1(occurrence_matrix)
normalized_occ_matrix_L2 = normalize_L2(occurrence_matrix)

# Normalisation de la matrice binaire
normalized_binary_matrix_L1 = normalize_L1(binary_matrix)

# Initialisation des matrices de distance
n_docs = len(documents)
distance_matrix_bray_curtis_occ_L1 = np.zeros((n_docs, n_docs))
distance_matrix_bray_curtis_occ_L2 = np.zeros((n_docs, n_docs))
distance_matrix_bray_curtis_binary = np.zeros((n_docs, n_docs))

# Matrices de distance pour Kullback-Leibler
distance_matrix_kl_occ_L1 = np.zeros((n_docs, n_docs))
distance_matrix_kl_occ_L2 = np.zeros((n_docs, n_docs))
distance_matrix_kl_binary = np.zeros((n_docs, n_docs))

# Calcul des distances entre tous les documents (Bray-Curtis et Kullback-Leibler)
for i in range(n_docs):
    for j in range(n_docs):
        # Distance Bray-Curtis pour la matrice d'occurrence normalisée L1
        distance_matrix_bray_curtis_occ_L1[i, j] = bray_curtis_distance(normalized_occ_matrix_L1[i], normalized_occ_matrix_L1[j])
        
        # Distance Bray-Curtis pour la matrice d'occurrence normalisée L2
        distance_matrix_bray_curtis_occ_L2[i, j] = bray_curtis_distance(normalized_occ_matrix_L2[i], normalized_occ_matrix_L2[j])
        
        # Distance Bray-Curtis pour la matrice binaire
        distance_matrix_bray_curtis_binary[i, j] = bray_curtis_distance(normalized_binary_matrix_L1[i], normalized_binary_matrix_L1[j])

        # Distance Kullback-Leibler pour la matrice d'occurrence normalisée L1
        distance_matrix_kl_occ_L1[i, j] = kullback_leibler_distance(normalized_occ_matrix_L1[i], normalized_occ_matrix_L1[j])
        
        # Distance Kullback-Leibler pour la matrice d'occurrence normalisée L2
        distance_matrix_kl_occ_L2[i, j] = kullback_leibler_distance(normalized_occ_matrix_L2[i], normalized_occ_matrix_L2[j])
        
        # Distance Kullback-Leibler pour la matrice binaire
        distance_matrix_kl_binary[i, j] = kullback_leibler_distance(normalized_binary_matrix_L1[i], normalized_binary_matrix_L1[j])

# Création des DataFrames pour afficher les résultats
distance_bray_curtis_occ_L1_df = pd.DataFrame(distance_matrix_bray_curtis_occ_L1, 
                                              columns=['ph1_', 'ph2_', 'ph3_'], 
                                              index=['ph1_', 'ph2_', 'ph3_'])

distance_bray_curtis_occ_L2_df = pd.DataFrame(distance_matrix_bray_curtis_occ_L2, 
                                              columns=['ph1_', 'ph2_', 'ph3_'], 
                                              index=['ph1_', 'ph2_', 'ph3_'])

distance_bray_curtis_binary_df = pd.DataFrame(distance_matrix_bray_curtis_binary, 
                                              columns=['ph1_', 'ph2_', 'ph3_'], 
                                              index=['ph1_', 'ph2_', 'ph3_'])

distance_kl_occ_L1_df = pd.DataFrame(distance_matrix_kl_occ_L1, 
                                      columns=['ph1_', 'ph2_', 'ph3_'], 
                                      index=['ph1_', 'ph2_', 'ph3_'])

distance_kl_occ_L2_df = pd.DataFrame(distance_matrix_kl_occ_L2, 
                                      columns=['ph1_', 'ph2_', 'ph3_'], 
                                      index=['ph1_', 'ph2_', 'ph3_'])

distance_kl_binary_df = pd.DataFrame(distance_matrix_kl_binary, 
                                      columns=['ph1_', 'ph2_', 'ph3_'], 
                                      index=['ph1_', 'ph2_', 'ph3_'])

# Affichage des matrices de distance
print("\nMatrice de Distance Bray-Curtis (Occurrences normalisées L1) :")
print(distance_bray_curtis_occ_L1_df)

print("\nMatrice de Distance Bray-Curtis (Occurrences normalisées L2) :")
print(distance_bray_curtis_occ_L2_df)

print("\nMatrice de Distance Bray-Curtis (Binaire normalisées L1) :")
print(distance_bray_curtis_binary_df)

print("\nMatrice de Distance Kullback-Leibler (Occurrences normalisées L1) :")
print(distance_kl_occ_L1_df)

print("\nMatrice de Distance Kullback-Leibler (Occurrences normalisées L2) :")
print(distance_kl_occ_L2_df)

print("\nMatrice de Distance Kullback-Leibler (Binaire normalisées L1) :")
print(distance_kl_binary_df)






Matrice de Distance Bray-Curtis (Occurrences normalisées L1) :
          ph1_      ph2_  ph3_
ph1_  0.000000  0.333333   1.0
ph2_  0.333333  0.000000   1.0
ph3_  1.000000  1.000000   0.0

Matrice de Distance Bray-Curtis (Occurrences normalisées L2) :
          ph1_      ph2_  ph3_
ph1_  0.000000  0.333333   1.0
ph2_  0.333333  0.000000   1.0
ph3_  1.000000  1.000000   0.0

Matrice de Distance Bray-Curtis (Binaire normalisées L1) :
      ph1_  ph2_  ph3_
ph1_   0.0   0.4   1.0
ph2_   0.4   0.0   1.0
ph3_   1.0   1.0   0.0

Matrice de Distance Kullback-Leibler (Occurrences normalisées L1) :
           ph1_       ph2_       ph3_
ph1_   0.000000   7.078030  21.465141
ph2_   7.078030   0.000000  21.465141
ph3_  21.234091  21.234091   0.000000

Matrice de Distance Kullback-Leibler (Occurrences normalisées L2) :
           ph1_       ph2_       ph3_
ph1_   0.000000  15.546542  47.457924
ph2_  15.546542   0.000000  47.457924
ph3_  53.878968  53.878968   0.000000

Matrice de Distance Kullback-

In [33]:
def normalize_l2(matrix):
    """Normalise chaque ligne de la matrice par sa norme L2."""
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)  # Calculer la norme L2 pour chaque ligne
    normalized_matrix = matrix / norms  # Diviser chaque ligne par sa norme L2
    return normalized_matrix

# 5. Calculer la distance euclidienne sur la matrice normalisée
def calculate_euclidean_distance(matrix):
    return squareform(pdist(matrix, metric='euclidean'))

# Documents
documents = [ph1_, ph2_, ph3_]
unique_tokens = preprocess_text(documents)

# Normalisation de la matrice par la norme L2
normalized_matrix_l2 = normalize_l2(occurrence_matrix)

# Calculer la distance euclidienne sur la matrice normalisée (L2)
distance_euclidean_l2 = calculate_euclidean_distance(normalized_matrix_l2)

# Créer un DataFrame pour afficher les distances
distance_euclidean_l2_df = pd.DataFrame(distance_euclidean_l2, 
                                        columns=['ph1_', 'ph2_', 'ph3_'],
                                        index=['ph1_', 'ph2_', 'ph3_'])


print("\nMatrice d'Occurrences :")
print(occurrence_matrix)

print("\nMatrice Normalisée par la Norme L2 :")
print(normalized_matrix_l2)

print("\nMatrice de Distance Euclidienne (Normalisée par la Norme L2) :")
print(distance_euclidean_l2_df)


Matrice d'Occurrences :
[[0 0 4 0 0 0 0 0 4 4 0 4 8]
 [0 0 0 0 4 0 0 4 0 4 0 4 8]
 [4 4 0 4 0 4 4 0 0 0 4 0 0]]

Matrice Normalisée par la Norme L2 :
[[0.         0.         0.35355339 0.         0.         0.
  0.         0.         0.35355339 0.35355339 0.         0.35355339
  0.70710678]
 [0.         0.         0.         0.         0.35355339 0.
  0.         0.35355339 0.         0.35355339 0.         0.35355339
  0.70710678]
 [0.40824829 0.40824829 0.         0.40824829 0.         0.40824829
  0.40824829 0.         0.         0.         0.40824829 0.
  0.        ]]

Matrice de Distance Euclidienne (Normalisée par la Norme L2) :
          ph1_      ph2_      ph3_
ph1_  0.000000  0.707107  1.414214
ph2_  0.707107  0.000000  1.414214
ph3_  1.414214  1.414214  0.000000


In [34]:

ph1_ = "The cat sat on the mat. The cat sat on the mat."
ph2_ = "The dog sat on the log. The dog sat on the log."
ph3_ = "Cats and dogs are great pets.Cats and dogs are great pets."

# Documents
documents = [ph1_, ph2_, ph3_]

# Prétraitement : Obtenir les tokens uniques
unique_tokens = preprocess_text(documents)

# Normalisation de la matrice en probabilités
normalized_matrix = normalize_matrix(occurrence_matrix)

# Calculer la distance euclidienne
distance_euclidean = calculate_euclidean_distance(normalized_matrix)

# Créer un DataFrame pour afficher les distances
distance_euclidean_df = pd.DataFrame(distance_euclidean, 
                                     columns=['ph1_', 'ph2_', 'ph3_'],
                                     index=['ph1_', 'ph2_', 'ph3_'])

# Afficher les résultats
print("\nMatrice d'Occurrences :")
print(occurrence_matrix)

print("\nMatrice Normalisée (Probabilités) :")
print(normalized_matrix)

print("\nMatrice de Distance Euclidienne (Normalisée en Probabilités) :")
print(distance_euclidean_df)



Matrice d'Occurrences :
[[0 0 4 0 0 0 0 0 4 4 0 4 8]
 [0 0 0 0 4 0 0 4 0 4 0 4 8]
 [4 4 0 4 0 4 4 0 0 0 4 0 0]]

Matrice Normalisée (Probabilités) :
[[0.         0.         0.16666667 0.         0.         0.
  0.         0.         0.16666667 0.16666667 0.         0.16666667
  0.33333333]
 [0.         0.         0.         0.         0.16666667 0.
  0.         0.16666667 0.         0.16666667 0.         0.16666667
  0.33333333]
 [0.16666667 0.16666667 0.         0.16666667 0.         0.16666667
  0.16666667 0.         0.         0.         0.16666667 0.
  0.        ]]

Matrice de Distance Euclidienne (Normalisée en Probabilités) :
          ph1_      ph2_     ph3_
ph1_  0.000000  0.333333  0.62361
ph2_  0.333333  0.000000  0.62361
ph3_  0.623610  0.623610  0.00000


In [36]:

# Documents
documents = [ph1_, ph2_, ph3_]

# Prétraitement : Obtenir les tokens uniques
unique_tokens = preprocess_text(documents)

# Normalisation de la matrice par la norme L2
normalized_matrix_l2 = normalize_l2(occurrence_matrix)

# Calculer la distance euclidienne sur la matrice normalisée (L2)
distance_euclidean_l2 = calculate_euclidean_distance(normalized_matrix_l2)

# Créer un DataFrame pour afficher les distances
distance_euclidean_l2_df = pd.DataFrame(distance_euclidean_l2, 
                                        columns=['ph1_', 'ph2_', 'ph3_'],
                                        index=['ph1_', 'ph2_', 'ph3_'])

# Afficher les résultats
print("\nMatrice d'Occurrences :")
print(occurrence_matrix)

print("\nMatrice Normalisée par la Norme L2 :")
print(normalized_matrix_l2)

print("\nMatrice de Distance Euclidienne (Normalisée par la Norme L2) :")
print(distance_euclidean_l2_df)


Matrice d'Occurrences :
[[0 0 4 0 0 0 0 0 4 4 0 4 8]
 [0 0 0 0 4 0 0 4 0 4 0 4 8]
 [4 4 0 4 0 4 4 0 0 0 4 0 0]]

Matrice Normalisée par la Norme L2 :
[[0.         0.         0.35355339 0.         0.         0.
  0.         0.         0.35355339 0.35355339 0.         0.35355339
  0.70710678]
 [0.         0.         0.         0.         0.35355339 0.
  0.         0.35355339 0.         0.35355339 0.         0.35355339
  0.70710678]
 [0.40824829 0.40824829 0.         0.40824829 0.         0.40824829
  0.40824829 0.         0.         0.         0.40824829 0.
  0.        ]]

Matrice de Distance Euclidienne (Normalisée par la Norme L2) :
          ph1_      ph2_      ph3_
ph1_  0.000000  0.707107  1.414214
ph2_  0.707107  0.000000  1.414214
ph3_  1.414214  1.414214  0.000000


In [37]:

# Phrases d'entrée
ph1_ = "The cat sat on the mat. The cat sat on the mat."
ph2_ = "The dog sat on the log. The dog sat on the log."
ph3_ = "Cats and dogs are great pets. Cats and dogs are great pets."


# 4. Normalisation par la norme L1
def normalize_l1(matrix):
    """Normalise chaque ligne de la matrice par sa norme L1."""
    norms = np.sum(np.abs(matrix), axis=1, keepdims=True)  # Calculer la norme L1 pour chaque ligne
    normalized_matrix = matrix / norms  # Diviser chaque ligne par sa norme L1
    return normalized_matrix

# 5. Calculer la distance de Manhattan sur la matrice normalisée
def calculate_manhattan_distance(matrix):
    return squareform(pdist(matrix, metric='cityblock'))

# Documents
documents = [ph1_, ph2_, ph3_]

# Prétraitement : Obtenir les tokens uniques
unique_tokens = preprocess_text(documents)


# Normalisation de la matrice par la norme L1
normalized_matrix_l1 = normalize_l1(occurrence_matrix)

# Calculer la distance de Manhattan sur la matrice normalisée (L1)
distance_manhattan_l1 = calculate_manhattan_distance(normalized_matrix_l1)

# Créer un DataFrame pour afficher les distances
distance_manhattan_l1_df = pd.DataFrame(distance_manhattan_l1, 
                                        columns=['ph1_', 'ph2_', 'ph3_'],
                                        index=['ph1_', 'ph2_', 'ph3_'])

# Afficher les résultats
print("\nMatrice d'Occurrences :")
print(occurrence_matrix)

print("\nMatrice Normalisée par la Norme L1 :")
print(normalized_matrix_l1)

print("\nMatrice de Distance de Manhattan (Normalisée par la Norme L1) :")
print(distance_manhattan_l1_df)



Matrice d'Occurrences :
[[0 0 4 0 0 0 0 0 4 4 0 4 8]
 [0 0 0 0 4 0 0 4 0 4 0 4 8]
 [4 4 0 4 0 4 4 0 0 0 4 0 0]]

Matrice Normalisée par la Norme L1 :
[[0.         0.         0.16666667 0.         0.         0.
  0.         0.         0.16666667 0.16666667 0.         0.16666667
  0.33333333]
 [0.         0.         0.         0.         0.16666667 0.
  0.         0.16666667 0.         0.16666667 0.         0.16666667
  0.33333333]
 [0.16666667 0.16666667 0.         0.16666667 0.         0.16666667
  0.16666667 0.         0.         0.         0.16666667 0.
  0.        ]]

Matrice de Distance de Manhattan (Normalisée par la Norme L1) :
          ph1_      ph2_  ph3_
ph1_  0.000000  0.666667   2.0
ph2_  0.666667  0.000000   2.0
ph3_  2.000000  2.000000   0.0


In [41]:
import re
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform

# Phrases d'entrée
ph1_ = "The cat sat on the mat. "
ph2_ = "The dog sat on the log. "
ph3_ = "Cats and dogs are great pets. "


# Documents
documents = [ph1_, ph2_, ph3_]

# Prétraitement : Obtenir les tokens uniques
unique_tokens = preprocess_text(documents)

# Normalisation de la matrice par la norme L1
normalized_matrix_l1 = normalize_l1(occurrence_matrix)

# Calculer la distance de Manhattan sur la matrice normalisée (L1)
distance_manhattan_l1 = calculate_manhattan_distance(normalized_matrix_l1)

# Créer un DataFrame pour afficher les distances
distance_manhattan_l1_df = pd.DataFrame(distance_manhattan_l1, 
                                        columns=['ph1_', 'ph2_', 'ph3_'],
                                        index=['ph1_', 'ph2_', 'ph3_'])

# Afficher les résultats
print("\nMatrice d'Occurrences :")
print(occurrence_matrix)

print("\nMatrice Normalisée par la Norme L1 :")
print(normalized_matrix_l1)

print("\nMatrice de Distance de Manhattan (Normalisée par la Norme L1) :")
print(distance_manhattan_l1_df)



Matrice d'Occurrences :
[[0 0 1 0 0 0 0 0 1 1 0 1 2]
 [0 0 0 0 1 0 0 1 0 1 0 1 2]
 [1 1 0 1 0 1 1 0 0 0 1 0 0]]

Matrice Normalisée par la Norme L1 :
[[0.         0.         0.16666667 0.         0.         0.
  0.         0.         0.16666667 0.16666667 0.         0.16666667
  0.33333333]
 [0.         0.         0.         0.         0.16666667 0.
  0.         0.16666667 0.         0.16666667 0.         0.16666667
  0.33333333]
 [0.16666667 0.16666667 0.         0.16666667 0.         0.16666667
  0.16666667 0.         0.         0.         0.16666667 0.
  0.        ]]

Matrice de Distance de Manhattan (Normalisée par la Norme L1) :
          ph1_      ph2_  ph3_
ph1_  0.000000  0.666667   2.0
ph2_  0.666667  0.000000   2.0
ph3_  2.000000  2.000000   0.0


In [43]:
ph1_ = "The cat sat on the mat. The cat sat on the mat.The cat sat on the mat. The cat sat on the mat."
ph2_ = "The dog sat on the log. The dog sat on the log.The dog sat on the log. The dog sat on the log."
ph3_ = "Cats and dogs are great pets. Cats and dogs are great pets.Cats and dogs are great pets. Cats and dogs are great pets."
# Documents
documents = [ph1_, ph2_, ph3_]

# Prétraitement : Obtenir les tokens uniques
unique_tokens = preprocess_text(documents)



# Normalisation de la matrice par la norme L1
normalized_matrix_l1 = normalize_l1(occurrence_matrix)

# Calculer la distance de Manhattan sur la matrice normalisée (L1)
distance_manhattan_l1 = calculate_manhattan_distance(normalized_matrix_l1)

# Créer un DataFrame pour afficher les distances
distance_manhattan_l1_df = pd.DataFrame(distance_manhattan_l1, 
                                        columns=['ph1_', 'ph2_', 'ph3_'],
                                        index=['ph1_', 'ph2_', 'ph3_'])

# Afficher les résultats
print("\nMatrice d'Occurrences :")
print(occurrence_matrix)

print("\nMatrice Normalisée par la Norme L1 :")
print(normalized_matrix_l1)

print("\nMatrice de Distance de Manhattan (Normalisée par la Norme L1) :")
print(distance_manhattan_l1_df)



Matrice d'Occurrences :
[[0 0 1 0 0 0 0 0 1 1 0 1 2]
 [0 0 0 0 1 0 0 1 0 1 0 1 2]
 [1 1 0 1 0 1 1 0 0 0 1 0 0]]

Matrice Normalisée par la Norme L1 :
[[0.         0.         0.16666667 0.         0.         0.
  0.         0.         0.16666667 0.16666667 0.         0.16666667
  0.33333333]
 [0.         0.         0.         0.         0.16666667 0.
  0.         0.16666667 0.         0.16666667 0.         0.16666667
  0.33333333]
 [0.16666667 0.16666667 0.         0.16666667 0.         0.16666667
  0.16666667 0.         0.         0.         0.16666667 0.
  0.        ]]

Matrice de Distance de Manhattan (Normalisée par la Norme L1) :
          ph1_      ph2_  ph3_
ph1_  0.000000  0.666667   2.0
ph2_  0.666667  0.000000   2.0
ph3_  2.000000  2.000000   0.0


In [45]:
# Documents
documents = [ph1_, ph2_, ph3_]

# Prétraitement : Obtenir les tokens uniques
unique_tokens = preprocess_text(documents)


# Normalisation de la matrice en probabilités
normalized_matrix = normalize_matrix(occurrence_matrix)

# Calculer la distance euclidienne
distance_euclidean = calculate_euclidean_distance(normalized_matrix)

# Créer un DataFrame pour afficher les distances
distance_euclidean_df = pd.DataFrame(distance_euclidean, 
                                     columns=['ph1_', 'ph2_', 'ph3_'],
                                     index=['ph1_', 'ph2_', 'ph3_'])

# Afficher les résultats
print("\nMatrice d'Occurrences :")
print(occurrence_matrix)

print("\nMatrice Normalisée (Probabilités) :")
print(normalized_matrix)

print("\nMatrice de Distance Euclidienne (Normalisée en Probabilités) :")
print(distance_euclidean_df)


Matrice d'Occurrences :
[[0 0 1 0 0 0 0 0 1 1 0 1 2]
 [0 0 0 0 1 0 0 1 0 1 0 1 2]
 [1 1 0 1 0 1 1 0 0 0 1 0 0]]

Matrice Normalisée (Probabilités) :
[[0.         0.         0.16666667 0.         0.         0.
  0.         0.         0.16666667 0.16666667 0.         0.16666667
  0.33333333]
 [0.         0.         0.         0.         0.16666667 0.
  0.         0.16666667 0.         0.16666667 0.         0.16666667
  0.33333333]
 [0.16666667 0.16666667 0.         0.16666667 0.         0.16666667
  0.16666667 0.         0.         0.         0.16666667 0.
  0.        ]]

Matrice de Distance Euclidienne (Normalisée en Probabilités) :
          ph1_      ph2_     ph3_
ph1_  0.000000  0.333333  0.62361
ph2_  0.333333  0.000000  0.62361
ph3_  0.623610  0.623610  0.00000


In [46]:
# Documents
documents = [ph1_, ph2_, ph3_]

# Prétraitement : Obtenir les tokens uniques
unique_tokens = preprocess_text(documents)


# Normalisation de la matrice par la norme L2
normalized_matrix_l2 = normalize_l2(occurrence_matrix)

# Calculer la distance euclidienne sur la matrice normalisée (L2)
distance_euclidean_l2 = calculate_euclidean_distance(normalized_matrix_l2)

# Créer un DataFrame pour afficher les distances
distance_euclidean_l2_df = pd.DataFrame(distance_euclidean_l2, 
                                        columns=['ph1_', 'ph2_', 'ph3_'],
                                        index=['ph1_', 'ph2_', 'ph3_'])

# Afficher les résultats
print("\nMatrice d'Occurrences :")
print(occurrence_matrix)

print("\nMatrice Normalisée par la Norme L2 :")
print(normalized_matrix_l2)

print("\nMatrice de Distance Euclidienne (Normalisée par la Norme L2) :")
print(distance_euclidean_l2_df)


Matrice d'Occurrences :
[[0 0 1 0 0 0 0 0 1 1 0 1 2]
 [0 0 0 0 1 0 0 1 0 1 0 1 2]
 [1 1 0 1 0 1 1 0 0 0 1 0 0]]

Matrice Normalisée par la Norme L2 :
[[0.         0.         0.35355339 0.         0.         0.
  0.         0.         0.35355339 0.35355339 0.         0.35355339
  0.70710678]
 [0.         0.         0.         0.         0.35355339 0.
  0.         0.35355339 0.         0.35355339 0.         0.35355339
  0.70710678]
 [0.40824829 0.40824829 0.         0.40824829 0.         0.40824829
  0.40824829 0.         0.         0.         0.40824829 0.
  0.        ]]

Matrice de Distance Euclidienne (Normalisée par la Norme L2) :
          ph1_      ph2_      ph3_
ph1_  0.000000  0.707107  1.414214
ph2_  0.707107  0.000000  1.414214
ph3_  1.414214  1.414214  0.000000


In [47]:
# Documents
documents = [ph1_, ph2_, ph3_]

# Prétraitement : Obtenir les tokens uniques
unique_tokens = preprocess_text(documents)



# Normalisation de la matrice par la norme L2
normalized_matrix_l2 = normalize_l2(occurrence_matrix)

# Calculer la distance de Manhattan sur la matrice normalisée (L2)
distance_manhattan_l2 = calculate_manhattan_distance(normalized_matrix_l2)

# Créer un DataFrame pour afficher les distances
distance_manhattan_l2_df = pd.DataFrame(distance_manhattan_l2, 
                                        columns=['ph1_', 'ph2_', 'ph3_'],
                                        index=['ph1_', 'ph2_', 'ph3_'])

# Afficher les résultats
print("\nMatrice d'Occurrences :")
print(occurrence_matrix)

print("\nMatrice Normalisée par la Norme L2 :")
print(normalized_matrix_l2)

print("\nMatrice de Distance de Manhattan (Normalisée par la Norme L2) :")
print(distance_manhattan_l2_df)


Matrice d'Occurrences :
[[0 0 1 0 0 0 0 0 1 1 0 1 2]
 [0 0 0 0 1 0 0 1 0 1 0 1 2]
 [1 1 0 1 0 1 1 0 0 0 1 0 0]]

Matrice Normalisée par la Norme L2 :
[[0.         0.         0.35355339 0.         0.         0.
  0.         0.         0.35355339 0.35355339 0.         0.35355339
  0.70710678]
 [0.         0.         0.         0.         0.35355339 0.
  0.         0.35355339 0.         0.35355339 0.         0.35355339
  0.70710678]
 [0.40824829 0.40824829 0.         0.40824829 0.         0.40824829
  0.40824829 0.         0.         0.         0.40824829 0.
  0.        ]]

Matrice de Distance de Manhattan (Normalisée par la Norme L2) :
          ph1_      ph2_     ph3_
ph1_  0.000000  1.414214  4.57081
ph2_  1.414214  0.000000  4.57081
ph3_  4.570810  4.570810  0.00000


In [49]:
import re
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform

# Phrases d'entrée
ph1_ = "The cat sat on the mat. "
ph2_ = "The dog sat on the log."
ph3_ = "Cats and dogs are great pets. "

# 1. Découper les phrases en mots
def split_into_words(text):
    """Divise le texte en mots en supprimant la ponctuation et en utilisant des espaces."""
    return re.findall(r'\b\w+\b', text.lower())

# 2. Prétraitement du texte pour obtenir les mots uniques
def preprocess_text(documents):
    unique_tokens = set()
    for doc in documents:
        tokens = split_into_words(doc)
        unique_tokens.update(tokens)
    return sorted(unique_tokens)  # Retourne une liste triée des mots uniques

# 3. Créer la matrice d'occurrences
def create_occurrence_matrix(documents, unique_tokens):
    occurrence_matrix = []
    
    for doc in documents:
        tokens = split_into_words(doc)
        occurrence_row = [tokens.count(token) for token in unique_tokens]
        occurrence_matrix.append(occurrence_row)

    return np.array(occurrence_matrix)

# 4. Normalisation par la probabilité (probabilité normale)
def normalize_probability(matrix):
    """Normalise la matrice d'occurrences en transformant les fréquences en probabilités."""
    row_sums = matrix.sum(axis=1, keepdims=True)  # Calculer la somme des occurrences pour chaque document
    probability_matrix = matrix / row_sums  # Diviser chaque élément par la somme de la ligne correspondante
    return probability_matrix

# 5. Normalisation par la norme L2
def normalize_l2(matrix):
    """Normalise chaque ligne de la matrice par sa norme L2."""
    norms = np.linalg.norm(matrix, ord=2, axis=1, keepdims=True)  # Calculer la norme L2 pour chaque ligne
    normalized_matrix = matrix / norms  # Diviser chaque ligne par sa norme L2
    return normalized_matrix

# 6. Calculer la distance de Cosinus
def calculate_cosine_distance(matrix):
    """Calcule la distance de Cosinus entre les documents."""
    return squareform(pdist(matrix, metric='cosine'))

# Documents
documents = [ph1_, ph2_, ph3_]

# Prétraitement : Obtenir les tokens uniques
unique_tokens = preprocess_text(documents)

# Créer la matrice d'occurrences
occurrence_matrix = create_occurrence_matrix(documents, unique_tokens)

# 7. Normalisation par la probabilité (normalisation en probabilités)
probability_matrix = normalize_probability(occurrence_matrix)

# 8. Normalisation par la norme L2
normalized_matrix_l2 = normalize_l2(occurrence_matrix)

# 9. Calcul des distances de Cosinus
distance_cosine_probability = calculate_cosine_distance(probability_matrix)
distance_cosine_l2 = calculate_cosine_distance(normalized_matrix_l2)

# Créer des DataFrames pour afficher les distances
distance_cosine_probability_df = pd.DataFrame(distance_cosine_probability, 
                                              columns=['ph1_', 'ph2_', 'ph3_'],
                                              index=['ph1_', 'ph2_', 'ph3_'])

distance_cosine_l2_df = pd.DataFrame(distance_cosine_l2, 
                                      columns=['ph1_', 'ph2_', 'ph3_'],
                                      index=['ph1_', 'ph2_', 'ph3_'])

# Afficher les résultats
print("\nMatrice de Distance de Cosinus (Normalisation par Probabilité) :")
print(distance_cosine_probability_df)

print("\nMatrice de Distance de Cosinus (Normalisation par la Norme L2) :")
print(distance_cosine_l2_df)



Matrice de Distance de Cosinus (Normalisation par Probabilité) :
      ph1_  ph2_  ph3_
ph1_  0.00  0.25   1.0
ph2_  0.25  0.00   1.0
ph3_  1.00  1.00   0.0

Matrice de Distance de Cosinus (Normalisation par la Norme L2) :
      ph1_  ph2_  ph3_
ph1_  0.00  0.25   1.0
ph2_  0.25  0.00   1.0
ph3_  1.00  1.00   0.0


In [57]:
import re
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform

# Trois premières phrases du discours de Jacques Chirac
ph1_ = "La confiance que vous venez de me témoigner, je veux y répondre en m'engageant dans l'action avec détermination."
ph2_ = "Mes chers compatriotes de métropole, d'outre-mer et de l'étranger,Nous venons de vivre un temps de grave inquiétude pour la Nation."
ph3_="Mais ce soir, dans un grand élan la France a réaffirmé son attachement aux valeurs de la République."

# 1. Découper les phrases en mots
def split_into_words(text):
    """Divise le texte en mots en supprimant la ponctuation et en utilisant des espaces."""
    return re.findall(r'\b\w+\b', text.lower())

# 2. Prétraitement du texte pour obtenir les mots uniques
def preprocess_text(documents):
    unique_tokens = set()
    for doc in documents:
        tokens = split_into_words(doc)
        unique_tokens.update(tokens)
    return sorted(unique_tokens)  # Retourne une liste triée des mots uniques

# 3. Créer la matrice d'occurrences
def create_occurrence_matrix(documents, unique_tokens):
    occurrence_matrix = []
    
    for doc in documents:
        tokens = split_into_words(doc)
        occurrence_row = [tokens.count(token) for token in unique_tokens]
        occurrence_matrix.append(occurrence_row)

    return np.array(occurrence_matrix)

# 4. Créer la matrice binaire
def create_binary_matrix(documents, unique_tokens):
    binary_matrix = []
    
    for doc in documents:
        tokens = split_into_words(doc)
        binary_row = [1 if token in tokens else 0 for token in unique_tokens]
        binary_matrix.append(binary_row)

    return np.array(binary_matrix)

# 5. Normalisation par la probabilité
def normalize_probability(matrix):
    row_sums = matrix.sum(axis=1, keepdims=True)
    probability_matrix = matrix / row_sums
    return probability_matrix

# 6. Normalisation par la norme L2
def normalize_l2(matrix):
    norms = np.linalg.norm(matrix, ord=2, axis=1, keepdims=True)
    normalized_matrix = matrix / norms
    return normalized_matrix

# 7. Calculer les distances (Manhattan, Euclidienne, Cosinus)
def calculate_distances(matrix, metric):
    return squareform(pdist(matrix, metric=metric))

# Documents
documents = [ph1_, ph2_, ph3_]

# Prétraitement : Obtenir les tokens uniques
unique_tokens = preprocess_text(documents)

# Créer les matrices d'occurrence et binaire
occurrence_matrix = create_occurrence_matrix(documents, unique_tokens)
binary_matrix = create_binary_matrix(documents, unique_tokens)

# Normalisation
occurrence_prob_matrix = normalize_probability(occurrence_matrix)
occurrence_l2_matrix = normalize_l2(occurrence_matrix)

binary_prob_matrix = normalize_probability(binary_matrix)
binary_l2_matrix = normalize_l2(binary_matrix)

# Calcul des distances
distances = {}

# Distances pour matrice d'occurrence normalisée par probabilité et norme L2
distances['occurrence_prob'] = {
    'manhattan': calculate_distances(occurrence_prob_matrix, 'cityblock'),
    'euclidean': calculate_distances(occurrence_prob_matrix, 'euclidean'),
    'cosine': calculate_distances(occurrence_prob_matrix, 'cosine')
}
distances['occurrence_l2'] = {
    'manhattan': calculate_distances(occurrence_l2_matrix, 'cityblock'),
    'euclidean': calculate_distances(occurrence_l2_matrix, 'euclidean'),
    'cosine': calculate_distances(occurrence_l2_matrix, 'cosine')
}

# Distances pour matrice binaire normalisée par probabilité et norme L2
distances['binary_prob'] = {
    'manhattan': calculate_distances(binary_prob_matrix, 'cityblock'),
    'euclidean': calculate_distances(binary_prob_matrix, 'euclidean'),
    'cosine': calculate_distances(binary_prob_matrix, 'cosine')
}
distances['binary_l2'] = {
    'manhattan': calculate_distances(binary_l2_matrix, 'cityblock'),
    'euclidean': calculate_distances(binary_l2_matrix, 'euclidean'),
    'cosine': calculate_distances(binary_l2_matrix, 'cosine')
}

def print_distance_matrices(distances, matrix_type):
    print(f"--- Distances pour la matrice {matrix_type} ---")
    for normalization, matrix in distances.items():  # Si `distances` est un dictionnaire de matrices
        if isinstance(matrix, dict):  # Vérifie si `matrix` est un dictionnaire avec types de distances
            print(f"Normalisation : {normalization}")
            for dist_type, mat in matrix.items():
                df = pd.DataFrame(mat, columns=['ph1_', 'ph2_', 'ph3_'], index=['ph1_', 'ph2_', 'ph3_'])
                print(f"Distance {dist_type.capitalize()} :")
                print(df)
        else:
            # Si la mtrice n'est pas un dictionnaire
            df = pd.DataFrame(matrix, columns=['ph1_', 'ph2_', 'ph3_'], index=['ph1_', 'ph2_', 'ph3_'])
            print(f"Normalisation : {normalization}")
            print(df)

# Affichage des distances
print_distance_matrices(distances['occurrence_prob'], "d'occurrence (probabilité)")
print_distance_matrices(distances['occurrence_l2'], "d'occurrence (norme L2)")
print_distance_matrices(distances['binary_prob'], "binaire (probabilité)")
print_distance_matrices(distances['binary_l2'], "binaire (norme L2)")



--- Distances pour la matrice d'occurrence (probabilité) ---
Normalisation : manhattan
          ph1_      ph2_      ph3_
ph1_  0.000000  1.733333  1.700000
ph2_  1.733333  0.000000  1.722222
ph3_  1.700000  1.722222  0.000000
Normalisation : euclidean
          ph1_      ph2_      ph3_
ph1_  0.000000  0.295804  0.299176
ph2_  0.295804  0.000000  0.303020
ph3_  0.299176  0.303020  0.000000
Normalisation : cosine
          ph1_      ph2_      ph3_
ph1_  0.000000  0.776393  0.800000
ph2_  0.776393  0.000000  0.739125
ph3_  0.800000  0.739125  0.000000
--- Distances pour la matrice d'occurrence (norme L2) ---
Normalisation : manhattan
          ph1_      ph2_      ph3_
ph1_  0.000000  7.358256  7.155418
ph2_  7.358256  0.000000  6.911042
ph3_  7.155418  6.911042  0.000000
Normalisation : euclidean
          ph1_      ph2_      ph3_
ph1_  0.000000  1.246109  1.264911
ph2_  1.246109  0.000000  1.215833
ph3_  1.264911  1.215833  0.000000
Normalisation : cosine
          ph1_      ph2_      p

In [27]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from math import log10

# Corpus de documents
documents = [
    "The cat sat on the mat.",
    "The dog sat on the log.",
    "Cats and dogs are great pets."
]

# Prétraitement du texte
vectorizer = CountVectorizer()  # Utiliser sans 'binary=True' pour avoir les occurrences
X_occ = vectorizer.fit_transform(documents)
terms = vectorizer.get_feature_names_out()

# TF binaire
vectorizer_binary = CountVectorizer(binary=True)  # Pour TF binaire
X_binary = vectorizer_binary.fit_transform(documents)
tf_binary = pd.DataFrame(X_binary.toarray(), columns=terms, index=['D1', 'D2', 'D3'])

# TF occurrence
tf_occ = pd.DataFrame(X_occ.toarray(), columns=terms, index=['D1', 'D2', 'D3'])

# TF occurrence normalisé (diviser chaque terme par le total des termes dans le document)
tf_occ_normalized = tf_occ.div(tf_occ.sum(axis=1), axis=0)

# Calcul de DF (Document Frequency) : Nombre de documents contenant chaque terme
df = (tf_occ > 0).sum(axis=0)

# Calcul de IDF (Inverse Document Frequency) avec log10
N = len(documents)  # Nombre total de documents
idf = np.log10(N / df)

# Affichage des matrices
print("TF Binaire:")
print(tf_binary)
print("\nTF Occurrence:")
print(tf_occ)
print("\nTF Occurrence Normalisé:")
print(tf_occ_normalized)
print("\nDocument Frequency (DF):")
print(df)
print("\nIDF (log10) pour chaque terme:")
print(idf)


TF Binaire:
    and  are  cat  cats  dog  dogs  great  log  mat  on  pets  sat  the
D1    0    0    1     0    0     0      0    0    1   1     0    1    1
D2    0    0    0     0    1     0      0    1    0   1     0    1    1
D3    1    1    0     1    0     1      1    0    0   0     1    0    0

TF Occurrence:
    and  are  cat  cats  dog  dogs  great  log  mat  on  pets  sat  the
D1    0    0    1     0    0     0      0    0    1   1     0    1    2
D2    0    0    0     0    1     0      0    1    0   1     0    1    2
D3    1    1    0     1    0     1      1    0    0   0     1    0    0

TF Occurrence Normalisé:
         and       are       cat      cats       dog      dogs     great  \
D1  0.000000  0.000000  0.166667  0.000000  0.000000  0.000000  0.000000   
D2  0.000000  0.000000  0.000000  0.000000  0.166667  0.000000  0.000000   
D3  0.166667  0.166667  0.000000  0.166667  0.000000  0.166667  0.166667   

         log       mat        on      pets       sat       the  


In [28]:
# Calcul des matrices TF-IDF
tfidf_binary = tf_binary * idf.values
tfidf_occ = tf_occ * idf.valuese
tfidf_occ_normalized = tf_occ_normalized * idf.values

# Affichage des matrices TF-IDF
print("TF-IDF Binaire:")
print(pd.DataFrame(tfidf_binary, columns=terms, index=['D1', 'D2', 'D3']))
print("\nTF-IDF Occurrence:")
print(pd.DataFrame(tfidf_occ, columns=terms, index=['D1', 'D2', 'D3']))
print("\nTF-IDF Occurrence Normalisé:")
print(pd.DataFrame(tfidf_occ_normalized, columns=terms, index=['D1', 'D2', 'D3']))


TF-IDF Binaire:
         and       are       cat      cats       dog      dogs     great  \
D1  0.000000  0.000000  0.477121  0.000000  0.000000  0.000000  0.000000   
D2  0.000000  0.000000  0.000000  0.000000  0.477121  0.000000  0.000000   
D3  0.477121  0.477121  0.000000  0.477121  0.000000  0.477121  0.477121   

         log       mat        on      pets       sat       the  
D1  0.000000  0.477121  0.176091  0.000000  0.176091  0.176091  
D2  0.477121  0.000000  0.176091  0.000000  0.176091  0.176091  
D3  0.000000  0.000000  0.000000  0.477121  0.000000  0.000000  

TF-IDF Occurrence:
         and       are       cat      cats       dog      dogs     great  \
D1  0.000000  0.000000  0.477121  0.000000  0.000000  0.000000  0.000000   
D2  0.000000  0.000000  0.000000  0.000000  0.477121  0.000000  0.000000   
D3  0.477121  0.477121  0.000000  0.477121  0.000000  0.477121  0.477121   

         log       mat        on      pets       sat       the  
D1  0.000000  0.477121  0.176

In [29]:
from scipy.spatial.distance import cdist

# Distance L1
distance_l1_binary = cdist(tfidf_binary, tfidf_binary, metric='cityblock')
distance_l1_occ = cdist(tfidf_occ, tfidf_occ, metric='cityblock')
distance_l1_occ_normalized = cdist(tfidf_occ_normalized, tfidf_occ_normalized, metric='cityblock')

print("\nDistance L1 (Binaire):")
print(distance_l1_binary)

print("\nDistance L1 (Occurrence):")
print(distance_l1_occ)

print("\nDistance L1 (Occurrence Normalisé):")
print(distance_l1_occ_normalized)



Distance L1 (Binaire):
[[0.         1.90848502 4.34524381]
 [1.90848502 0.         4.34524381]
 [4.34524381 4.34524381 0.        ]]

Distance L1 (Occurrence):
[[0.         1.90848502 4.52133507]
 [1.90848502 0.         4.52133507]
 [4.52133507 4.52133507 0.        ]]

Distance L1 (Occurrence Normalisé):
[[0.         0.31808084 0.75355585]
 [0.31808084 0.         0.75355585]
 [0.75355585 0.75355585 0.        ]]


In [30]:
# Distance L2
distance_l2_binary = cdist(tfidf_binary, tfidf_binary, metric='euclidean')
distance_l2_occ = cdist(tfidf_occ, tfidf_occ, metric='euclidean')
distance_l2_occ_normalized = cdist(tfidf_occ_normalized, tfidf_occ_normalized, metric='euclidean')

print("\nDistance L2 (Binaire):")
print(distance_l2_binary)

print("\nDistance L2 (Occurrence):")
print(distance_l2_occ)

print("\nDistance L2 (Occurrence Normalisé):")
print(distance_l2_occ_normalized)



Distance L2 (Binaire):
[[0.         0.95424251 1.38353964]
 [0.95424251 0.         1.38353964]
 [1.38353964 1.38353964 0.        ]]

Distance L2 (Occurrence):
[[0.         0.95424251 1.41675909]
 [0.95424251 0.         1.41675909]
 [1.41675909 1.41675909 0.        ]]

Distance L2 (Occurrence Normalisé):
[[0.         0.15904042 0.23612652]
 [0.15904042 0.         0.23612652]
 [0.23612652 0.23612652 0.        ]]


In [31]:
# Distance Cosinus
distance_cosine_binary = cdist(tfidf_binary, tfidf_binary, metric='cosine')
distance_cosine_occ = cdist(tfidf_occ, tfidf_occ, metric='cosine')
distance_cosine_occ_normalized = cdist(tfidf_occ_normalized, tfidf_occ_normalized, metric='cosine')

print("\nDistance Cosinus (Binaire):")
print(distance_cosine_binary)

print("\nDistance Cosinus (Occurrence):")
print(distance_cosine_occ)

print("\nDistance Cosinus (Occurrence Normalisé):")
print(distance_cosine_occ_normalized)



Distance Cosinus (Binaire):
[[0.00000000e+00 8.30344598e-01 1.00000000e+00]
 [8.30344598e-01 0.00000000e+00 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.11022302e-16]]

Distance Cosinus (Occurrence):
[[0.00000000e+00 7.09905324e-01 1.00000000e+00]
 [7.09905324e-01 0.00000000e+00 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.11022302e-16]]

Distance Cosinus (Occurrence Normalisé):
[[0.         0.70990532 1.        ]
 [0.70990532 0.         1.        ]
 [1.         1.         0.        ]]


In [32]:
# Distance Bray-Curtis
distance_bray_curtis_binary = cdist(tfidf_binary, tfidf_binary, metric='braycurtis')
distance_bray_curtis_occ = cdist(tfidf_occ, tfidf_occ, metric='braycurtis')
distance_bray_curtis_occ_normalized = cdist(tfidf_occ_normalized, tfidf_occ_normalized, metric='braycurtis')

print("\nDistance Bray-Curtis (Binaire):")
print(distance_bray_curtis_binary)

print("\nDistance Bray-Curtis (Occurrence):")
print(distance_bray_curtis_occ)

print("\nDistance Bray-Curtis (Occurrence Normalisé):")
print(distance_bray_curtis_occ_normalized)



Distance Bray-Curtis (Binaire):
[[0.        0.6436641 1.       ]
 [0.6436641 0.        1.       ]
 [1.        1.        0.       ]]

Distance Bray-Curtis (Occurrence):
[[0.         0.57532749 1.        ]
 [0.57532749 0.         1.        ]
 [1.         1.         0.        ]]

Distance Bray-Curtis (Occurrence Normalisé):
[[0.         0.57532749 1.        ]
 [0.57532749 0.         1.        ]
 [1.         1.         0.        ]]
